### ISSUE TITLE
Possibility to automate gathering framedata?

### ISSUE THREAD

**Issue by MariaArtemis** [yakiimoninja/baiken#8]
The way I understand it, the way its structured now is that you have to automatically update the .json files to add framedata, which while it functions atm, is prone to missing things that change, etc. For example, a while ago I added the total duration of ROTKM, but this is not reflected in the bot yet.

However, Dustloop does have a publicly available API, which I know how to use. Would it be of interest to use this API to populate the data the bot has access to, instead of relying on the author remembering all the changes that happen?

**Comment by yakiimoninja** [comment]
> is prone to missing things that change

So for changes on dustloop to take affect an owner of the bot needs to manually run the `/update` command for all 3 `frames` ,`images`, `info` for it to update.
I have done it this way for mainly 2 reasons:
1. To keep an eye out for breaking changes. Like moves changing names thus invalidating any related and manually created                aliases.
2. Because I haven't though of a better way of doing it.

I'm not opposed to suggestion of implementing a better solution isn't there still a risk of unsupervised breaking changes because of the nature of contribution on dustloop?

Lastly I think you're suggesting of a implementing a crate like [wikibase](https://crates.io/crates/wikibase)?
I am absolutely willing and open to discuss more.
One thing to note is that I am just a hobbyist and not really a dev so I'm most probably lacking fundamental knowledge on the matter.

**Comment by MariaArtemis** [comment]
> So for changes on dustloop to take affect an owner of the bot needs to manually run the /update command for all 3 frames ,images, info for it to update.

Yes, which means you have to manually update the json files so that the bot gets new frame data whenever stuff changes.

> I'm not opposed to suggestion of implementing a better solution but isn't there still a risk of unsupervised breaking changes because of the nature of contribution on dustloop?

There is, but any actual errors is rare. Moves are never changed after a characters page gets done, and no one is vandalizing the frame datas. If incorrect frame data is found, its fixed, which means the bot can then again just get the new frame data whenever that arrives.

>Lastly I think you're suggesting of a implementing a crate like [wikibase](https://crates.io/crates/wikibase)?

No, I am talking about operating with the [Dustloop API](https://www.dustloop.com/w/Special:ApiSandbox), which allows one to access the internal SQL database containing all the frame data and such. Wikibase doesnt do this as far as I'm aware. But this is doable with [reqwest](https://crates.io/crates/reqwest) and [serde_json](https://github.com/serde-rs/json)

**Comment by MariaArtemis** [comment]
Oh, I see! Then my solution I was wondering about is already implemented! Just probably should autoupdate at set intervals to ensure that all the frame data is collected

**Comment by yakiimoninja** [comment]
Closing as implemented with 0.23.0
